import type { NodePgDatabase } from 'drizzle-orm/node-postgres';

export async function up(_db: NodePgDatabase): Promise<void> {
  // Drizzle Kit generates SQL migrations from backend/src/db/schema.ts.
}

export async function down(_db: NodePgDatabase): Promise<void> {
  // Rollback SQL is generated by Drizzle migration tooling.
}
